query GetCreatorTokens($start: DateTime!, $end: DateTime!) {
  creatorTokens(
    where: { createdAt_gte: $start, createdAt_lte: $end }
    orderBy: createdAt_ASC
  ) {
    createdAt
  }
}

query GetCrtTransactions(
  $start: Int!
  $end: Int!
  $limit: Int!
  $offset: Int!
) {
  ammTransactions(
    where: { createdIn_gte: $start, createdIn_lte: $end }
    limit: $limit
    offset: $offset
  ) {
    transactionType
    pricePaid
  }
}
query GetCrtTransactionsWithBlock(
  $start: Int!
  $end: Int!
  $limit: Int!
  $offset: Int!
) {
  ammTransactions(
    where: { createdIn_gte: $start, createdIn_lte: $end }
    limit: $limit
    offset: $offset
  ) {
    createdIn
    transactionType
    pricePaid
  }
}

query GetRevenueSplitAmounts($until: Int!) {
  events(
    where: {
      data: { isTypeOf_eq: "CreatorTokenRevenueSplitIssuedEventData" }
      inBlock_lte: $until
    }
  ) {
    data {
      ... on CreatorTokenRevenueSplitIssuedEventData {
        revenueShare {
          stakers {
            earnings
          }
        }
      }
    }
  }
}
