query GetElectedCouncils(
  $where: ElectedCouncilWhereInput
  $offset: Int
  $limit: Int
) {
  electedCouncils(where: $where, orderBy: createdAt_ASC, offset: $offset, limit: $limit) {
    ...ElectedCouncilFields
    __typename
  }
}

query GetCouncilReward(
  $where:RewardPaymentEventWhereInput,
  $limit:Int,
  $offset:Int
){
  rewardPaymentEvents(
    where:$where 
    limit:$limit 
    offset:$offset 
    orderBy:createdAt_ASC
    ) {
        paidBalance
        inBlock
        councilMember{
          memberId
        }
    }
}

query GetCouncilRewardTotalCount(
  $where:RewardPaymentEventWhereInput
){
  rewardPaymentEventsConnection(
    where:$where
  ){
    totalCount
  }
}

query GetCouncilReFill(
  $where: BudgetRefillEventWhereInput,
  $limit:Int,
  $offset:Int
) {
  budgetRefillEvents(
    where:$where
    limit:$limit
    offset:$offset
    orderBy:createdAt_ASC
  ) {
    balance
    inBlock
  }
}

query GetCouncilReFillTotalCount(
  $where:BudgetRefillEventWhereInput
) {
  budgetRefillEventsConnection(
    where:$where
  ) {
    totalCount
  }
}

fragment ElectedCouncilFields on ElectedCouncil {
  id
  electedAtBlock
  electedAtTime
  electedAtNetwork
  endedAtBlock
  endedAtTime
  endedAtNetwork
  councilElections {
    cycleId
  }

  councilMembers {
    ...CouncilMemberFields
  }
}

fragment CouncilMemberFields on CouncilMember {
  id
  member {
    ...MemberFields
    councilMembers {
      __typename
    }
  }
  unpaidReward
  stake
}
