query GetElectionRoundWithUniqueID($where: ElectionRoundWhereUniqueInput!) {
  electionRoundByUniqueInput(where:$where){
    id
    cycleId
    castVotes{
      stake
      stakeLocked
    }
    candidates{
      votePower
      member{
				handle
      }
    }
  }
}

