query GetNftIssuedCount($where: NftIssuedEventWhereInput) {
  nftIssuedEventsConnection(where: $where) {
    totalCount
  }
}

query GetNftIssued($where: NftIssuedEventWhereInput, $limit:Int, $offset:Int){
  nftIssuedEvents(where:$where limit:$limit offset:$offset orderBy:createdAt_ASC){
    id
    createdAt
  }
}

query GetNftSaleCount($where: NftBoughtEventWhereInput) {
  nftBoughtEventsConnection(where: $where) {
    totalCount
  }
}

query GetNftSales(
  $where: NftBoughtEventWhereInput
  $orderBy: [NftBoughtEventOrderByInput!]
  $offset: Int
  $limit: Int
) {
  nftBoughtEvents(
    offset: $offset
    limit: $limit
    where: $where
    orderBy: $orderBy
  ) {
    ...NftBoughtEventField
  }
}

fragment NftBoughtEventField on NftBoughtEvent {
  videoId
  memberId
  price
}

query GetAuctionsTotalCount(
  $where:AuctionWhereInput
) {
  auctionsConnection(where:$where){
    totalCount
  }
}

query GetAuctions(
  $offset: Int
  $limit: Int
  $where: AuctionWhereInput
  $orderBy: [AuctionOrderByInput!]
) {
  auctions(offset: $offset, limit: $limit, where: $where, orderBy: $orderBy) {
    nftId
    winningMemberId
    startingPrice
    buyNowPrice
    isCanceled
    isCompleted
    topBid {
      ...BidField
    }
  }
}

fragment BidField on Bid {
  bidderId
  nftId
  amount
  isCanceled
}
