query GetStorageDataObjects(
  $offset: Int
  $limit: Int
  $where: StorageDataObjectWhereInput
) {
  storageDataObjects(
    limit: $limit
    offset: $offset
    where: $where
    orderBy:createdAt_ASC
  ) {
    createdAt
    size
  }
}

query GetStorageDataObjectsCount($where: StorageDataObjectWhereInput) {
  storageDataObjectsConnection(where: $where) { 
    totalCount
  }
}

query GetStorageBuckets($where:StorageBucketWhereInput){
  storageBuckets(where:$where){
    dataObjectsCount
    dataObjectsSize
    createdAt
  }
}
